### ISSUE TITLE
a few problems while running estimate_trf.py

### ISSUE THREAD

**Issue by deltaphase** [Eelbrain/Alice#5]
Hi,

Thank you very much for sharing this library. I initially tried this pipline using five subjects' EEG data of the Alice dataset on my MacBook Pro (10.15.6), and each code runs fine!

Then, I would like to analzye all EEG files of the Alice dataset on Windows, and I was unable to launch "estimate_trf.py". I got a runtime error message as follows:

        RuntimeError:
                 An attempt has been made to start a new process before the
                 current process has finished its bootstrapping phase.
 
                 This probably means that you are not using fork to start your
                 child processes and you have forgotten to use the proper idiom
                 in the main module:
 
                     if __name__ == '__main__':
                         freeze_support()
                         ...
 
                 The "freeze_support()" line can be omitted if the program
                 is not going to be frozen to produce an executable.
 

To overcome this problem, I follow this solution: https://github.com/tomopy/tomopy/issues/356
Now, the first two TRF models (envelope and envelope+onset) of the first subject were fitted and saved, but the pipline stopped at "Estimating: S01 ~ acoustic". Would you mind helping me out? Thanks!

**Comment by deltaphase** [comment]
update:

Now the estimate_trf.py pipline works fine after excluding models that are related to gammatone and gammatone_onsets. I am still working on why these model can not be fitted.

**Comment by christianbrodbeck** [comment]
What happens when you try to fit the gammatone models? I think Windows is generally a bit more finicky with multiprocessing. I've recently also heard from someone that the fitting TRFs with multiprocessing on runs much slower on Windows, did you notice that?

**Comment by christianbrodbeck** [comment]
So is this #6 all you had to do to get it to run on Windows? (It looks like more changes because of the indent, but all I did was insert `if __name__ == '__main__':`)

**Comment by deltaphase** [comment]
After interupting pipline of `estimate_trf.py`, I got some messages like this:

> 
> (mne) E:\Alice\analysis>python 03_estimate_trfs.py                                                                                                                                                           Estimating: S01 ~ envelope                                                                                                                                                                                   Estimating: S01 ~ envelope+onset                                                                                                                                                                             Estimating: S01 ~ acoustic                                                                                                                                                                                   Fitting models:   0%|                                                                         | 0/1220 [00:00<?, ?it/s]Traceback (most recent call last):                                                      File "E:\Alice\analysis\03_estimate_trfs.py", line 102, in <module>                                                                                                                                        Process SpawnProcess-37:                                                                                                                                                                                     Traceback (most recent call last):                                                                                                                                                                             File "C:\Users\Kevin\anaconda3\envs\mne\lib\multiprocessing\process.py", line 315, in _bootstrap                                                                                                               self.run()                                                                                                                                                                                                 File "C:\Users\Kevin\anaconda3\envs\mne\lib\multiprocessing\process.py", line 108, in run                                                                                                                      self._target(*self._args, **self._kwargs)                                                                                                                                                                  File "C:\Users\Kevin\anaconda3\envs\mne\lib\site-packages\eelbrain\_trf\_boosting.py", line 1167, in boosting_worker                                                                                           h = boost(y[i_y], x, x_pads, splits[i_split], i_start, i_stop, delta, mindelta, error, selective_stopping)                                                                                                 File "C:\Users\Kevin\anaconda3\envs\mne\lib\site-packages\eelbrain\_trf\_boosting.py", line 1092, in boost                                                                                                     generate_options(y_error, x, x_pads, x_active, split.train, i_start, i_start_by_x, i_stop_by_x, delta_error_func, delta, new_error, new_sign) 
> KeyboardInterrupt
> 

Hope this information can help!

**Comment by christianbrodbeck** [comment]
I can reproduce the issue (on Windows), but don't have a good solution yet. It's strange that the error occurs for gammatone but not for envelope+onsets, because at that level the only difference should be whether the predictor is a `2 x n_times` or an `8 x n_times` array. It seems to be an issue with `multiprocessing`, because when I disable multiprocessing the progress bar advances (call `eelbrain.configure(0)` before starting the boosting).

**Comment by deltaphase** [comment]
Thanks. After adding `eelbrain.configure(0)`', gammatone models are fitted!


> ... It's strange that the error occurs for gammatone but not for envelope+onsets, because at that level the only difference should be whether the predictor is a `2 x n_times` or an `8 x n_times` array. It seems to be an issue with `multiprocessing`, because when I disable multiprocessing the progress bar advances (call `eelbrain.configure(0)` before starting the boosting).

I am having the same thought as you. I will discuss this with my lab membeers and will get back to you on this if we have further ideas. In any case, I think that this issue is closed. Thanks!

**Comment by christianbrodbeck** [comment]
Running on a single core is not ideal for larger projects...

I've tried replacing `Cython` in the inner function (`generate_options`) with `numba`, but that does not seem to change this... (https://github.com/christianbrodbeck/Eelbrain/tree/numba-boosting).

**Comment by deltaphase** [comment]
Thank you for working on this subject. I would like to share two thoughts.

1. I read this thread https://github.com/cython/cython/issues/2014# and insert `setattr(sys, 'frozen', True)` and `freeze_support()` after `if __name__ == '__main__':`, so the relevent codes look like this:

```
if __name__ == '__main__':
    setattr(sys, 'frozen', True)
    multiprocessing.freeze_support()
    for subject in SUBJECTS:
```

Then I have this error message:

> (mne) E:\Alice\analysis>python 03_estimate_trfs.py
> Estimating: S14 ~ acoustic
> Fitting models:   0%|                                                                         | 0/1220 [00:00<?, ?it/s]unknown option --multiprocessing-fork
> usage: C:\Users\Kevin\anaconda3\envs\mne\python.exe [option] ... [-c cmd | -m mod | file | -] [arg] ...
> Try `python -h' for more information.
> 

Would you have an idea how of this proplem?

2. I am thinking to split the 8 x n_times array into eight 1xn_times arrays. Such as, changing this:
` 'acoustic': [gammatone, gammatone_onsets]`
into something like this:
` 'acoustic': [gammatone1, gammatone2, gammatone3,... gammatone_onset7, gammatone_onset8]`

I will try the second approach and see how it goes. Thanks!

**Comment by deltaphase** [comment]
UPDATE:

It turns out that the following approach does not work:

> 2. I am thinking of splitting the 8 x n_times array into eight 1xn_times arrays. Such as, changing this:
>    ` 'acoustic': [gammatone, gammatone_onsets]`
>    into something like this:
>    ` 'acoustic': [gammatone1, gammatone2, gammatone3,... gammatone_onset7, gammatone_onset8]`
> 

While building a model with more than 3 predictors, the progress bar stops after finishing the first three or four TRFs ....

**Comment by christianbrodbeck** [comment]
1. Regarding `--multiprocessing-fork`, the multiprocessing start method is determined here https://github.com/christianbrodbeck/Eelbrain/blob/master/eelbrain/_config.py#L34 you could try to change it here, although I thought fork wasn't even an option on Windows (https://docs.python.org/3/library/multiprocessing.html?highlight=multiprocessing#contexts-and-start-methods)
2. Internally, the different predictors will be concatenated again into an `8 x n_times` array (or `16 x n_times`) before starting the part that involves multiprocessing, so I would be surprised if you got anything different.

**Comment by deltaphase** [comment]
Thanks for the suggestion. Now I have changed the multiprocessing start method to spawn, and it seems that it is not necessary to call `setattr` and  `freeze_support()`. So in the results that I describe below, `setattr` and  `freeze_support()` are not used.

1) running the estimate_trf.py  after inserting `__name__ == '__main__':`: gammtone models are not fitted. The progress bar does not advance.

2) after inserting `__name__ == '__main__':`, and splitting the 8 x n_times array into eight 1xn_times arrays: It looks like that while running the pipeline, the progress slows down and then it is stuck.

3) doing 1) and 2) and disable multiprocessing (call eelbrain.configure(0)): gammtone models are fitted and saved.

4) I suspect that the resources are not cleaned up after finishing each subprocess, so I insert a few codes to call queue.close() and quese.join_thread() after the line No.611 `pbar.close()` in  `_boosting.py`:

>         if CONFIG['n_workers']:
>             job_queue.close()
>             result_queue.close()
>             job_queue.join_thread()
>             result_queue.join_thread()

It seems to speed up the process, meaning that the progress does not slow down ... but it is still stuck after a few runs...

**Comment by christianbrodbeck** [comment]
If you have the ability to, the easiest work around for now might be to install Linux on your PCs. On Linux I've been using this without multiprocessing issues for a long time.

**Comment by deltaphase** [comment]
> If you have the ability to, the easiest work around for now might be to install Linux on your PCs. On Linux I've been using this without multiprocessing issues for a long time.

Thanks, I will try this solution!

**Comment by deltaphase** [comment]
> > If you have the ability to, the easiest work around for now might be to install Linux on your PCs. On Linux I've been using this without multiprocessing issues for a long time.
> 
> Thanks, I will try this solution!

I installed Ubuntu on WSL. The pipeline runs on Linux on my PC now, and everything looks fine!
